### ISSUE TITLE
why "Finally, it uses Stable Diffusion 2 to generate an image, based on the title and each slide heading." have been deleted？ 

### ISSUE THREAD

**Issue by szh-max** [barun-saha/slide-deck-ai#1]
why "Finally, it uses Stable Diffusion 2 to generate an image, based on the title and each slide heading." have been deleted？

**Comment by barun-saha** [comment]
Hi,

Thanks for your interest in SlideDeck AI.

The primary reason for discontinuing image generation is the cost of operations. Also, I wasn't sure how useful the users found this feature.

The code is still available, only commented out, in case anyone wants to run it themselves.

**Comment by barun-saha** [comment]
Closing inactive issue.
